export const AGENTS = [
  { id: 1,  name: "Regime Detection",             category: "direction",         tier: 1 },
  { id: 2,  name: "Trend Structure",              category: "direction",         tier: 1 },
  { id: 3,  name: "Market Breadth",               category: "direction",         tier: 1 },
  { id: 4,  name: "Market Momentum",              category: "direction",         tier: 1 },
  { id: 5,  name: "Trend Following",              category: "direction",         tier: 1 },
  { id: 6,  name: "HMM Market State",             category: "direction",         tier: 2 },
  { id: 7,  name: "News Analyst",                 category: "news_macro",        tier: 1 },
  { id: 8,  name: "Earnings Sentiment",           category: "news_macro",        tier: 1 },
  { id: 9,  name: "Event Detection",              category: "news_macro",        tier: 1 },
  { id: 10, name: "Macro News Impact",            category: "news_macro",        tier: 1 },
  { id: 11, name: "Macro Analyst",                category: "news_macro",        tier: 1 },
  { id: 12, name: "Federal Reserve",              category: "news_macro",        tier: 1 },
  { id: 13, name: "Global Liquidity",             category: "news_macro",        tier: 2 },
  { id: 14, name: "Dollar Strength",              category: "news_macro",        tier: 1 },
  { id: 15, name: "Sector Rotation",              category: "institutional",     tier: 1 },
  { id: 16, name: "Dark Pool Flow",               category: "institutional",     tier: 2 },
  { id: 17, name: "13F Accumulation",             category: "institutional",     tier: 1 },
  { id: 18, name: "Whale Options Flow",           category: "institutional",     tier: 2 },
  { id: 19, name: "Insider Transactions",         category: "institutional",     tier: 1 },
  { id: 20, name: "ETF Flow Intelligence",        category: "institutional",     tier: 1 },
  { id: 21, name: "Put Call Parity",              category: "strength",          tier: 1 },
  { id: 22, name: "Gamma Exposure",               category: "strength",          tier: 1 },
  { id: 23, name: "Factor Crowding",              category: "strength",          tier: 2 },
  { id: 24, name: "Uncertainty",                  category: "strength",          tier: 1 },
  { id: 25, name: "Relative Strength",            category: "strength",          tier: 1 },
  { id: 26, name: "VIX Structure",                category: "strength",          tier: 1 },
  { id: 27, name: "Correlation Decay",            category: "exit_reversal",     tier: 2 },
  { id: 28, name: "Cross Asset Correlation",      category: "exit_reversal",     tier: 1 },
  { id: 29, name: "Market Leadership",            category: "exit_reversal",     tier: 1 },
  { id: 30, name: "Signal Aggregation",           category: "prediction_layer",  tier: 1 },
  { id: 31, name: "Ensemble Model",               category: "prediction_layer",  tier: 1 },
  { id: 32, name: "Confidence Scoring",           category: "prediction_layer",  tier: 1 },
  { id: 33, name: "Final Prediction Engine",      category: "prediction_layer",  tier: 1 },
  { id: 34, name: "Options OI Structure",         category: "additional",        tier: 1 },
  { id: 35, name: "Crude Oil Intelligence",       category: "commodity",         tier: 1 },
  { id: 36, name: "Gold & Precious Metals",       category: "commodity",         tier: 1 },
  { id: 37, name: "Natural Gas Intelligence",     category: "commodity",         tier: 1 },
  { id: 38, name: "Silver Intelligence",          category: "commodity",         tier: 1 },
  { id: 39, name: "Copper Intelligence",          category: "commodity",         tier: 1 },
  { id: 40, name: "Commodity Momentum",           category: "commodity",         tier: 1 },
  { id: 41, name: "Commodity Sentiment",          category: "commodity",         tier: 2 },
  { id: 42, name: "Commodity Flow & Positioning", category: "commodity",         tier: 2 },
];

export const AGENT_CATEGORIES = [
  "direction", "news_macro", "institutional",
  "strength", "exit_reversal", "prediction_layer", "additional", "commodity"
];
